apiVersion: v1
kind: Service
metadata:
  name: med-config
  namespace: medback
  labels:
    app.kubernetes.io/name: med-config
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: medback-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: med-config
    app.kubernetes.io/component: infrastructure
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      protocol: TCP
