apiVersion: v1
kind: Service
metadata:
  name: med-postgres
  namespace: medback
  labels:
    app.kubernetes.io/name: med-postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: medback-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: med-postgres
    app.kubernetes.io/component: database
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
