apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: med-mongodb-pvc
  namespace: medback
  labels:
    app.kubernetes.io/name: med-mongodb
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: medback-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
