spring:
  application:
    name: MED_CHATBOT_SERVICE
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false

server:
  port: 8084
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health, refresh
