apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: medback
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: observability
    app.kubernetes.io/part-of: medback-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
