apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: medback
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/component: middleware
    app.kubernetes.io/part-of: medback-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
