apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: medback
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/component: middleware
    app.kubernetes.io/part-of: medback-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/component: middleware
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
      protocol: TCP
