apiVersion: v1
kind: Service
metadata:
  name: med-chatboot-service
  namespace: medback
  labels:
    app.kubernetes.io/name: med-chatboot-service
    app.kubernetes.io/component: business
    app.kubernetes.io/part-of: medback-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: med-chatboot-service
    app.kubernetes.io/component: business
  ports:
    - name: http
      port: 8084
      targetPort: http
      protocol: TCP
