apiVersion: v1
kind: Service
metadata:
  name: med-gateway
  namespace: medback
  labels:
    app.kubernetes.io/name: med-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: medback-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: med-gateway
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
