apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: med-core-storage-pvc
  namespace: medback
  labels:
    app.kubernetes.io/name: med-core-storage
    app.kubernetes.io/component: business
    app.kubernetes.io/part-of: medback-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
