apiVersion: apps/v1
kind: Deployment
metadata:
  name: med-gateway
  namespace: medback
  labels:
    app.kubernetes.io/name: med-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: medback-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: med-gateway
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: med-gateway
        app.kubernetes.io/component: gateway
        app.kubernetes.io/part-of: medback-platform
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: med-gateway
          image: kheireddinemechergui/med-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: medback-global-config
            - secretRef:
                name: medback-global-secret
          env:
            - name: SPRING_APPLICATION_NAME
              value: med-gateway-service
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
